[package]
name = "partial-tar-brotli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
brotli = "6.0.0"
clap = { version = "4.5.16", features = ["derive"] }
serde_json = "1.0.125"
tar = "0.4.41"
